swagger: "2.0"
info:
  title: Lang-UK NER
  description: Named entity extractor APIs for UK language with MITIE under the hood and model trained by Lang-UK
  contact:
    name: Mike Chaliy
    email: mike@chaliy.name
  version: "1.0.0"
  license:
    name: MIT
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
responses:
      '400':
        description: Input is malformed or invalid
      '500':
        description: Internal error
      '405':
        description: Method is not allowed
paths:
  '/ner':
    get:
      summary: Information about current NER
      operationId: info
      tags:
        - ner
      responses:
        '200':
          description: The request has succeeded
          schema:
            $ref: '#/definitions/InfoResponse'
    post:
      summary: Extract named entities from tokenized input
      operationId: extract
      x-taskClass: ner
      x-taskAlgo: mitie
      x-taskModel: uk
      tags:
        - ner
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/ExtractRequest'
      responses:
        '200':
          description: The request has succeeded
          schema:
            $ref: '#/definitions/ExtractResponse'

definitions:
  InfoResponse:
    properties:
      tags:
        description: NER tags suppored by this instance of extractor
        type: array
        items:
          type: string
  ExtractRequest:
    properties:
      text:
        description: Optional text to be tokenized by default MITIE tokenizer
        type: string
      tokens:
        description: List of tokens to extract named entities from
        type: array
        items:
          type: string
  ExtractResponse:
    properties:
      entities:
        type: array
        items:
          $ref: '#/definitions/ExtractedEntry'
      text:
        type: string
      tokens:
        type: array
        items:
          type: string
  ExtractedEntry:
    properties:
      label:
        type: string
      score:
        type: number
        format: double
      tag:
        type: string
  Text:
    type: string
