swagger: '2.0'
info:
  title: 'Lang-UK NER'
  description: 'Named entity extractor APIs for UK language with MITIE under the hood and model trained by Lang-UK'
  contact:
    name: 'API Support'
    email: 'mike@chaliy.name'
  version: '1.0.0'
host: TBD
basePath: '/',
schemes:
  - http
  - https
consumes:
  - 'application/json'
produces:
  - 'application/json'
responses:
      '400':
        description: 'Input is malformed or invalid'
      '500':
        description: 'Internal error'
      '405':
        description: 'Method is not allowed'
  }
paths:
  '/ner':
    post:
      summary: 'Extract named entities from input'
      operationId: 'extract'
      tags:
        - ner
      parameters:
        in: body
        name: body
        required: true
      responses:
          '200':
            description: 'The request has succeeded',
            schema:
              '$ref': `#/definitions/response`
